const masterProduct = [
  {
    id: "examination-gloves",
    name: "Examination Gloves",
    content: "NON-STERILE",
    form: "Gloves",
    mg: "100 Pcs",
    mrp: 1000,
    rate: 238,
    unitOfSale: "Box",
    unitName: "Piece",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153234/Examination-Gloves_nq1dus.png",
  },
  {
    id: "m-vit",
    name: "M-VIT",
    content: "Multi Vitamin Infusion",
    form: "Injection",
    mg: "10 ml",
    mrp: 36,
    rate: 9,
    unitOfSale: "Box",
    unitName: "Vial",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153253/M-VIT_e7mbn5.png",
  },
  {
    id: "ulcerlink-gel",
    name: "Ulcerlink Gel",
    content: "Choline Salicylate, Lignocaine HCl & Benzalkonium Chloride Solution Gel",
    form: "Gel",
    mg: "15 gm",
    mrp: 80,
    rate: 10.92,
    unitOfSale: "Tube",
    unitName: "Tube",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197545/Ulcerlink-Gel_lmiqpk.png",
  },
  {
    id: "venolok-23g",
    name: "VENOLOK",
    content: "Premium Odin SCALP VEIN SET 23G",
    form: "Scalp Vein Set",
    mg: "100 Units",
    mrp: 80,
    rate: 6.136,
    unitOfSale: "Box",
    unitName: "Piece",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153218/VENOLOK_nv6ty5.png",
  },
  {
    id: "venolok-22g",
    name: "VENOLOK",
    content: "Premium Odin SCALP VEIN SET 22G",
    form: "Scalp Vein Set",
    mg: "100 Units",
    mrp: 80,
    rate: 6.136,
    unitOfSale: "Box",
    unitName: "Piece",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153218/VENOLOK_nv6ty5.png",
  },
  {
    id: "enzyna",
    name: "Enzyna",
    content: "Alpha Amylase, Papain & Activated Charcoal Tablets",
    form: "Tablet",
    mg: "20x15 Tabs",
    mrp: 42,
    rate: 14.56,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153231/Enzyna_eniy52.png",
  },
  {
    id: "atpl-soul-2ml-24g",
    name: "ATPL SOUL 2ml",
    content: "HYPODERMIC SYRINGE WITH NEEDLE",
    form: "Syringe",
    mg: "2 ml 24G",
    mrp: 25,
    rate: 2.379,
    unitOfSale: "Box",
    unitName: "Piece",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153198/ATPL-SOUL-2ml_dkgimk.png",
  },
  {
    id: "atpl-soul-5ml-24g",
    name: "ATPL SOUL 5ml",
    content: "HYPODERMIC SYRINGE WITH NEEDLE",
    form: "Syringe",
    mg: "5 ml 24G",
    mrp: 35,
    rate: 2.795,
    unitOfSale: "Box",
    unitName: "Piece",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153200/ATPL-SOUL-5ml_epykrj.png",
  },
  {
    id: "atpl-soul-10ml",
    name: "ATPL SOUL 10ml",
    content: "HYPODERMIC SYRINGE WITH NEEDLE",
    form: "Syringe",
    mg: "10 ml",
    mrp: 55,
    rate: 5.85,
    unitOfSale: "Box",
    unitName: "Piece",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153212/ATPL-SOUL-10ml_xlp9jl.png",
  },
  {
    id: "zydiclo",
    name: "Zydiclo",
    content: "Diclofenac Sodium Injection I.P.",
    form: "Injection",
    mg: "3 ml",
    mrp: 5.6,
    rate: 4.225,
    unitOfSale: "Box",
    unitName: "Ampoule",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153207/Zydiclo_jsir7n.png",
  },
  {
    id: "e-phyllin",
    name: "E-PHYLLIN",
    content: "Etophylline & Theophylline Anhydrous Tablets",
    form: "Tablet",
    mg: "100 Tabs",
    mrp: 50,
    rate: 35.49,
    unitOfSale: "Bottle",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153236/E-PHYLLIN_i27pqt.png",
  },
  {
    id: "otilab",
    name: "OTILAB",
    content: "Beclomethasone Dipropionate, Clotrimazole, Lignocaine HCl & Gentamicin Sulphate Ear Drops",
    form: "Drops",
    mg: "10 ml",
    mrp: 111,
    rate: 28.6,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153247/OTILAB_txgniu.png",
  },
  {
    id: "challenge-pore",
    name: "CHALLENGE-PORE",
    content: "Adhesive Tape Non-Woven Support B.P.",
    form: "Tape",
    mg: "1 Roll",
    mrp: 750,
    rate: 300.3,
    unitOfSale: "Box",
    unitName: "Roll",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197544/CHALLENGE-PORE_pt7jqo.png",
  },
  {
    id: "cifbax",
    name: "Cifbax",
    content: "Ciprofloxacin & Hydroxypropyl Methyl Cellulose Eye/Ear Drops",
    form: "Drops",
    mg: "10 ml",
    mrp: 17.24,
    rate: 10.14,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153224/Cifbax_jwovkg.png",
  },
  {
    id: "lopro",
    name: "Lopro",
    content: "Loperamide Hydrochloride Tablets IP 2 mg",
    form: "Tablet",
    mg: "2 mg",
    mrp: 25.98,
    rate: 1.82,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153237/Lopro_e8z4rv.png",
  },
  {
    id: "rolled-fabrics-7-5cm",
    name: "ROLLED FABRICS",
    content: "7.5 CM X 8 M",
    form: "Bandage",
    mg: "7.5cm x 8m",
    mrp: 450,
    rate: 110.5,
    unitOfSale: "Roll",
    unitName: "Roll",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153255/ROLLED-FABRICS-7.5cm.jpg_s85k6x.png",
  },
  {
    id: "rolled-fabrics-5cm",
    name: "ROLLED FABRICS",
    content: "5 CM X 8 Y",
    form: "Bandage",
    mg: "5cm x 8y",
    mrp: 300,
    rate: 73.58,
    unitOfSale: "Roll",
    unitName: "Roll",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153255/ROLLED-FABRICS-5cm_ve6qhl.png",
  },
  {
    id: "mohini-zigzag-cotton",
    name: "Mohini's Zigzag Cotton",
    content: "ABSORBENT COTTON WOOL (I.P.)",
    form: "Cotton",
    mg: "500gm",
    mrp: 600,
    rate: 238.55,
    unitOfSale: "Pack",
    unitName: "Pack",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153241/Mohini-Cotton_i3s9es.png",
  },
  {
    id: "kofnol",
    name: "Kofnol",
    content: "CHEWABLE COUGH TABS",
    form: "Tablet",
    mg: "1000 Tabs",
    mrp: 351,
    rate: 214.5,
    unitOfSale: "Jar",
    unitName: "Jar",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153225/Kofnol_bq7di5.png",
  },
  {
    id: "cocef-100-dt",
    name: "Cocef-100 DT",
    content: "Cefixime Dispersible Tablets I.P.",
    form: "Tablet",
    mg: "100 mg",
    mrp: 85,
    rate: 35.49,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153208/Cocef-100-DT_hruhbv.png",
  },
  {
    id: "ranitac-150",
    name: "Ranitac-150",
    content: "Ranitidine Hydrochloride Tablets I.P. 150 mg",
    form: "Tablet",
    mg: "150 mg",
    mrp: 14.96,
    rate: 8.19,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153252/Ranitac-150_v1uayt.png",
  },
  {
    id: "coughlink-am",
    name: "Coughlink-AM",
    content: "Ambroxol Hydrochloride, Guaiphenesin, Terbutaline Sulphate & Menthol Syrup",
    form: "Syrup",
    mg: "100ml",
    mrp: 95,
    rate: 16.38,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153215/Coughlink-AM_orlyxc.png",
  },
  {
    id: "coldlink-ds",
    name: "Coldlink-DS",
    content: "Paracetamol, Phenylephrine Hydrochloride & Chlorpheniramine Maleate Suspension",
    form: "Syrup",
    mg: "60ml",
    mrp: 60,
    rate: 16.38,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153216/Coldlink-DS_v3vsew.png",
  },
  {
    id: "l-cetlink",
    name: "L-Cetlink",
    content: "Levocetirizine Dihydrochloride Syrup",
    form: "Syrup",
    mg: "60ml",
    mrp: 40,
    rate: 11.18,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153235/L-Cetlink_lh9yie.png",
  },
  {
    id: "polymol-ds",
    name: "Polymol-DS",
    content: "Paracetamol Paediatric Oral Suspension IP",
    form: "Syrup",
    mg: "60ml",
    mrp: 45,
    rate: 15.6,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153251/Polymol-DS_e9srck.png",
  },
  {
    id: "ibulink-p",
    name: "Ibulink-P",
    content: "Ibuprofen & Paracetamol Suspension",
    form: "Syrup",
    mg: "60ml",
    mrp: 60,
    rate: 15.6,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153237/Ibulink-P_x9wkmw.png",
  },
  {
    id: "coughlink-dex-plus",
    name: "Coughlink-Dex Plus",
    content: "Dextromethorphan Hydrobromide, Phenylephrine Hydrochloride & Chlorpheniramine Maleate Syrup",
    form: "Syrup",
    mg: "100ml",
    mrp: 107.8,
    rate: 17.745,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761360764/Coughlink-Dex-Plush_yfglz9.png",
  },
  {
    id: "coughlink-ls",
    name: "Coughlink-LS",
    content: "Ambroxol Hcl, Levosalbutamol Sulphate & Guaiphenesin Syrup",
    form: "Syrup",
    mg: "60ml",
    mrp: 65,
    rate: 13.65,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153212/Coughlink-LS_akykxm.png",
  },
  {
    id: "oflolink-ms",
    name: "OFLOLINK-MS",
    content: "Ofloxacin, Metronidazole Benzoate & Simethicone Oral Suspension",
    form: "Suspension",
    mg: "30 ml",
    mrp: 110,
    rate: 15.6,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153254/OFLOLINK-MS_ym68al.png",
  },
  {
    id: "nasovid-adult",
    name: "Nasovid Adult",
    content: "Xylometazoline Hydrochloride Nasal Solution IP",
    form: "Nasal Spray",
    mg: "10 ml",
    mrp: 58,
    rate: 17.68,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153243/Nasovid-Adult_edotqo.png",
  },
  {
    id: "zybend",
    name: "Zybend",
    content: "Albendazole Oral Suspension IP",
    form: "Suspension",
    mg: "10 ml",
    mrp: 20,
    rate: 11.05,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153200/Zybend.jpg_syy7sz.png",
  },
  {
    id: "azitek-100",
    name: "Azitek 100",
    content: "Azithromycin Oral Suspension I.P. 100 mg",
    form: "Suspension",
    mg: "15 ml",
    mrp: 33.39,
    rate: 24.5,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153202/Azitek-100_z5nf1m.png",
  },
  {
    id: "azitek-200",
    name: "Azitek 200",
    content: "Azithromycin Oral Suspension I.P. 200 mg",
    form: "Suspension",
    mg: "15 ml",
    mrp: 58.29,
    rate: 27.95,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153202/Azitek-200_gp17o7.png",
  },
  {
    id: "cefilink-50",
    name: "Cefilink 50",
    content: "Cefixime Oral Suspension IP 50 mg",
    form: "Suspension",
    mg: "30 ml",
    mrp: 48,
    rate: 18.2,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153204/Cefilink-50_glxh2u.png",
  },
  {
    id: "anvil",
    name: "ANVIL",
    content: "PHENIRAMINE MALEATE INJECTION I.P.",
    form: "Injection",
    mg: "30 ml",
    mrp: 33,
    rate: 17.55,
    unitOfSale: "Vial",
    unitName: "Vial",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153212/ANVIL-INJ_ygms4a.png",
  },
  {
    id: "scorpus",
    name: "SCORPUS",
    content: "RANITIDINE H.C.L. INJECTION IP",
    form: "Injection",
    mg: "30 ml",
    mrp: 33.0,
    rate: 18.98,
    unitOfSale: "Vial",
    unitName: "Vial",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153206/SCORPUS-INJ_tyeczg.png",
  },
  {
    id: "paramol-ad",
    name: "PARAMOL-AD",
    content: "PARACETAMOL INJECTION",
    form: "Injection",
    mg: "30 ml",
    mrp: 51,
    rate: 29.9,
    unitOfSale: "Vial",
    unitName: "Vial",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153251/PARAMOL-AD_pilpxa.png",
  },
  {
    id: "dexa-ad",
    name: "DEXA-AD",
    content: "Dexamethasone Sodium Phosphate INJECTION I.P.",
    form: "Injection",
    mg: "30 ml",
    mrp: 28.95,
    rate: 28.95,
    unitOfSale: "Vial",
    unitName: "Vial",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153219/DEXA-AD_utwriz.png",
  },
  {
    id: "spasmin",
    name: "SPASMIN",
    content: "DICYCLOMINE H.C.L. INJECTION IP",
    form: "Injection",
    mg: "30 ml",
    mrp: 51,
    rate: 20.47,
    unitOfSale: "Vial",
    unitName: "Vial",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153194/SPASMIN_q29nus.png",
  },
  {
    id: "anatron",
    name: "ANATRON",
    content: "Ondansetron Injection I.P.",
    form: "Injection",
    mg: "30 ml",
    mrp: 51,
    rate: 18.98,
    unitOfSale: "Vial",
    unitName: "Vial",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153197/ANATRON_ss0ndv.png",
  },
  {
    id: "paracetamol-bag",
    name: "Paracetamol",
    content: "Paracetamol Tablet I.P.",
    form: "Tablet",
    mg: "500 mg",
    mrp: 500,
    rate: 266.5,
    unitOfSale: "Bag",
    unitName: "Bag",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153246/Paracetamol_kssn3j.png",
  },
  {
    id: "diagyl-200",
    name: "Diagyl-200",
    content: "Metronidazole Tablets I.P.",
    form: "Tablet",
    mg: "200 mg",
    mrp: 200,
    rate: 98.9,
    unitOfSale: "Bag",
    unitName: "Bag",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153218/Diagyl-200_ogcoqc.png",
  },
  {
    id: "clomin",
    name: "CLOMIN",
    content: "Dicyclomine HCL Tablets I.P. 20 mg",
    form: "Tablet",
    mg: "20 mg",
    mrp: 150,
    rate: 75,
    unitOfSale: "Bag",
    unitName: "Bag",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761360764/Clomin_wfrocc.png",
  },
  {
    id: "salbutamol",
    name: "Salbutamol",
    content: "Salbutamol Tablets I.P. 2 Mg",
    form: "Tablet",
    mg: "2 mg",
    mrp: 100,
    rate: 52,
    unitOfSale: "Bag",
    unitName: "Bag",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761360768/Salbutamol_z4t2th.png",
  },
  {
    id: "restin-0-5",
    name: "RESTIN 0.5",
    content: "ALPRAZOLAM 0.5 MG TABLETS I.P.",
    form: "Tablet",
    mg: "0.5 mg",
    mrp: 300,
    rate: 143.3,
    unitOfSale: "Bag",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761360764/Restin_cmo35h.png",
  },
  {
    id: "dexzone",
    name: "Dexzone",
    content: "Dexamethasone Tablets I.P.",
    form: "Tablet",
    mg: "0.5 mg",
    mrp: 80,
    rate: 42.25,
    unitOfSale: "Bag",
    unitName: "Bag",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153216/Dexzone_cztajm.png",
  },
  {
    id: "super-rest",
    name: "SUPER REST",
    content: "DICLOFENAC SODIUM TABLET I.P.",
    form: "Tablet",
    mg: "50 mg",
    mrp: 200,
    rate: 54.6,
    unitOfSale: "Bag",
    unitName: "Bag",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153195/SUPER-REST_clmva1.png",
  },
  {
    id: "sober-infusion-set",
    name: "SOBER INFUSION SET",
    content: "INFUSION SET",
    form: "Infusion Set",
    mg: "50 Pcs",
    mrp: 120,
    rate: 7.644,
    unitOfSale: "Bag",
    unitName: "Piece",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761360765/Sober-Infusion-Set_ijvj78.png",
  },
  {
    id: "nimbu-c",
    name: "NIMBU-C",
    content: "Ascorbic Acid Tablets I.P. 100 mg",
    form: "Tablet",
    mg: "100 mg",
    mrp: 134,
    rate: 109.2,
    unitOfSale: "Bag",
    unitName: "Bag",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761361196/Nimbu-C_uh6vte.png",
  },
  {
    id: "moxi",
    name: "MOXI",
    content: "EYE DROPS",
    form: "Drops",
    mg: "10ml",
    mrp: 176,
    rate: 19.76,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153244/MOXI_rozf80.png",
  },
  {
    id: "moxi-d",
    name: "MOXI-D",
    content: "EYE DROPS",
    form: "Drops",
    mg: "10ml",
    mrp: 148,
    rate: 20.8,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153246/MOXI-D_hkn5mc.png",
  },
  {
    id: "oneclav-1-2g",
    name: "Oneclav 1.2 g",
    content: "Amoxycillin and Potassium Clavulanate Injection IP 1.2g",
    form: "Injection",
    mg: "1.2g",
    mrp: 139.65,
    rate: 68.25,
    unitOfSale: "Vial",
    unitName: "Vial",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153243/Oneclav_yfis4v.png",
  },
  {
    id: "diclotek-aq",
    name: "Diclotek AQ",
    content: "Diclofenac Sodium Injection IP (10 x 5 x 1ml Ampoules)",
    form: "Ampoules",
    mg: "75mg/ml",
    mrp: 22,
    rate: 4.095,
    unitOfSale: "Box",
    unitName: "Box",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153225/Diclotek_AQ_srv3i8.png",
  },
  {
    id: "trolyte",
    name: "Trolyte",
    content: "Oral Rehydration Salts IP (21.8 gm x 25 Sachets)",
    form: "Sachet",
    mg: "21.8 gm",
    mrp: 22,
    rate: 5.07,
    unitOfSale: "Box",
    unitName: "Box",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153195/Trolyte_gevni7.png",
  },
  {
    id: "salmo-4-lose",
    name: "Salmo-4(Lose)",
    content: "Salbutamol Sulphate Tablets I.P. 4 mg.",
    form: "Tablet",
    mg: "4mg",
    mrp: 100,
    rate: 44.85,
    unitOfSale: "Bottle",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153200/Salmo_sf1t2o.png",
  },
  {
    id: "avildom",
    name: "Avildom",
    content: "PHENIRAMINE MALEATE TABLETS I.P. 25 MG",
    form: "Tablet",
    mg: "25 mg",
    mrp: 150,
    rate: 52.0,
    unitOfSale: "Bottle",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761153205/Avildom_akanil.png",
  },
  {
    id: "soulspas-p-syrup",
    name: "Soulspas-P Syrup",
    content: "Dicyclomine & Paracetamol Suspension",
    form: "Syrup",
    mg: "60ml",
    mrp: 65,
    rate: 18,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197901/SOSPAS-P_yketek.jpg",
  },
  {
    id: "soulpro",
    name: "SoulPro",
    content: "Comprehensive Nutrition Supplement",
    form: "Protein Powder",
    mg: "200gm",
    mrp: 255,
    rate: 74,
    unitOfSale: "Jar",
    unitName: "Jar",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197903/SOUL_PRO_mzz87s.jpg",
  },
  {
    id: "soul-vita",
    name: "Soul Vita",
    content: "Dextrose and Ascorbic Acid with Zinc Powder",
    form: "Powder",
    mg: "105gm",
    mrp: 75,
    rate: 18,
    unitOfSale: "Box",
    unitName: "Box",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197906/SOUL_VITA_rhgc3f.jpg",
  },
  {
    id: "soulcef-dt-tab",
    name: "Soulcef DT TAB",
    content: "Cefixime Dispersible Tablets I.P.",
    form: "Tablet",
    mg: "1x10",
    mrp: 109,
    rate: 51,
    unitOfSale: "Strip",
    unitsPerStrip: 10,
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197903/SOULCEF_DT_lzlzza.png",
  },
  {
    id: "soulcet-m-tab",
    name: "Soulcet M TAB",
    content: "Montelukast sodium and Levocetrizine Hydrochloride Tablet IP 5/10 mg",
    form: "Tablet",
    mg: "1x10",
    mrp: 65,
    rate: 14,
    unitOfSale: "Strip",
    unitsPerStrip: 10,
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197903/SOULCET-M_bqonrz.jpg",
  },
  {
    id: "soulcid-20-cap",
    name: "Soulcid-20 CAP",
    content: "Omeprazole Gastro-resistant Capsules IP 20mg",
    form: "Capsule",
    mg: "20x15",
    mrp: 45,
    rate: 11,
    unitOfSale: "Strip",
    unitsPerStrip: 15,
    unitName: "Capsule",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197905/SOULCID_fk02xi.png",
  },
  {
    id: "soulcold-ds-syrup",
    name: "Soulcold-DS Syrup",
    content: "Paracetamol, Phenylephrine Hydrochloride, Chlorpheniramine Maleate Syrup",
    form: "Syrup",
    mg: "60ml",
    mrp: 60,
    rate: 19,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197904/Soulcold_DS_jsw0kg.jpg",
  },
  {
    id: "soulcure-am-syrup",
    name: "Soulcure AM Syrup",
    content: "Levosalbutamol, Ambroxol Hydrochloride & Guaiphenesin Syrup",
    form: "Syrup",
    mg: "60ml",
    mrp: 64,
    rate: 21,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197899/SOULCURE-AM_wdiwjq.jpg",
  },
  {
    id: "soulgesic-syrup",
    name: "Soulgesic Syrup",
    content: "Ibuprofen and Paracetamol Suspension",
    form: "Syrup",
    mg: "60ml",
    mrp: 64,
    rate: 19,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197899/Soulgesic_aszkyx.jpg",
  },
  {
    id: "soulmef-ds",
    name: "Soulmef-DS",
    content: "Mefenamic Acid & Paracetamol Suspension 100mg/250mg",
    form: "Suspension",
    mg: "60ml",
    mrp: 75,
    rate: 18,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197905/SOULMEF-DS_wr62fv.png",
  },
  {
    id: "soulmef-tab",
    name: "Soulmef TAB",
    content: "Mefenamic Acid & Dicyclomine HCL",
    form: "Tablet",
    mg: "1x10",
    mrp: 45,
    rate: 8,
    unitOfSale: "Strip",
    unitsPerStrip: 10,
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197906/SOULMEF_ub3uua.png",
  },
  {
    id: "soulmox-cv-syrup",
    name: "Soulmox-CV Syrup",
    content: "Amoxycillin & Potassium Clavulanate",
    form: "Dry Syrup",
    mg: "30ml",
    mrp: 68,
    rate: 36,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197906/Soulmox_CV-_Dry_Syrup_lvvx6f.jpg",
  },
  {
    id: "soulnac-p",
    name: "Soulnac-P",
    content: "Aceclofenac & Paracetamol",
    form: "Tablet",
    mg: "1x10",
    mrp: 75,
    rate: 8,
    unitOfSale: "Strip",
    unitsPerStrip: 10,
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197908/SOULNAC-P_r4jxlu.jpg",
  },
  {
    id: "soulpod-200-tab",
    name: "Soulpod 200 TAB",
    content: "Cefpodoxime Proxetil",
    form: "Tablet",
    mg: "1x10",
    mrp: 150,
    rate: 66,
    unitOfSale: "Strip",
    unitsPerStrip: 10,
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197907/SOULPOD_bzqr9k.jpg",
  },
  {
    id: "soulrab-dsr-cap",
    name: "Soulrab DSR CAP",
    content: "Rabeprazole & Domperidone",
    form: "Capsule",
    mg: "1x10",
    mrp: 80,
    rate: 14,
    unitOfSale: "Strip",
    unitsPerStrip: 10,
    unitName: "Capsule",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197908/SOULRAB-DSR_xlr2cm.jpg",
  },
  {
    id: "soulsera-ap-tab",
    name: "Soulsera AP TAB",
    content: "Aceclofenac, Paracetamol & Serratiopeptidase",
    form: "Tablet",
    mg: "1x10",
    mrp: 110,
    rate: 15,
    unitOfSale: "Strip",
    unitsPerStrip: 10,
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197909/SOULSERA-AP_q1cltx.jpg",
  },
  {
    id: "soulsetron-syrup",
    name: "Soulsetron Syrup",
    content: "Ondansetron Oral Solution",
    form: "Syrup",
    mg: "30ml",
    mrp: 60,
    rate: 15,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197908/SOULSETRON-_syrup_pxuiaf.jpg",
  },
  {
    id: "soulsetron-tab",
    name: "Soulsetron TAB",
    content: "Ondansetron Orally Tablets",
    form: "Tablet",
    mg: "1x10",
    mrp: 52,
    rate: 6,
    unitOfSale: "Strip",
    unitsPerStrip: 10,
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197909/Soulsetron_tjhssf.jpg",
  },
  {
    id: "urisoul-syp",
    name: "URISOUL Syp",
    content: "Disodium Hydrogen Citrate Syrup",
    form: "Syrup",
    mg: "100ml",
    mrp: 125,
    rate: 23,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197909/URISOUL_petay9.jpg",
  },
  {
    id: "cold-s",
    name: "Cold S",
    content: "Paracetamol,Phenylephrrine Tablets Hydrochloride & Chlorpheniramine Maleate Tablets",
    form: "Tablet",
    mg: "",
    mrp: 50,
    rate: 8,
    unitOfSale: "Strip",
    unitsPerStrip: 10,
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1761197906/COLD-S_sipfwn.png",
  },
  {
    id: "budison-0-5",
    name: "BUDISON 0.5",
    content: "Budesonide Nebuliser Suspension BP (0.5 mg)",
    form: "Respules",
    mg: "0.5 mg",
    mrp: 26.15,
    rate: 7.5,
    unitOfSale: "Box",
    unitName: "Respule",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524622/BUDISON_0.5_ougjf9.png",
  },
  {
    id: "azicip-250",
    name: "Azicip 250",
    content: "Azithromycin Tablets IP 250 mg",
    form: "Tablet",
    mg: "250 mg",
    mrp: 74.77,
    rate: 44.38,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524617/Azicip_250_ngfz4y.png",
  },
  {
    id: "deflamic-6",
    name: "Deflamic-6",
    content: "Deflazacort Tablets 6 mg",
    form: "Tablet",
    mg: "6 mg",
    mrp: 187.5,
    rate: 16.88,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524625/Deflamic-6_ql1yhp.png",
  },
  {
    id: "citicad",
    name: "Citicad",
    content: "Cetirizine Hydrochloride Tablets IP",
    form: "Tablet",
    mg: "10 mg",
    mrp: 19.73,
    rate: 2.19,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524624/Citicad_lrl6tz.png",
  },
  {
    id: "alkarant-syrup",
    name: "ALKARANT Syrup",
    content: "Disodium Hydrogen Citrate Syrup",
    form: "Syrup",
    mg: "100ml",
    mrp: 135.94,
    rate: 16.88,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524616/ALKARANT-100ml_tryest.png",
  },
  {
    id: "elcemet-500",
    name: "Elcemet-500",
    content: "20 x 10 Tablets",
    form: "Tablet",
    mg: "500 mg",
    mrp: 22.51,
    rate: 6.88,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524628/Elcemet-500_agagcz.png",
  },
  {
    id: "bifirant",
    name: "Bifirant",
    content: "Prebiotic & Probiotic with Zinc Sulphate Sachet",
    form: "Sachet",
    mg: "1gm",
    mrp: 31.14,
    rate: 4.69,
    unitOfSale: "Box",
    unitName: "Sachet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524618/Bifirant_rjrvsl.png",
  },
  {
    id: "bitazone",
    name: "Bitazone",
    content: "Ceftriaxone Injection IP (1000 mg)",
    form: "Injection",
    mg: "1000 mg",
    mrp: 66.64,
    rate: 18.75,
    unitOfSale: "Vial",
    unitName: "Vial",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524620/Bitazone-1000_mg_r1r8ul.png",
  },
  {
    id: "chymothal-forte",
    name: "Chymothal Forte",
    content: "Trypsin-Chymotrypsin 100000 A.U. Tablets",
    form: "Tablet",
    mg: "100000 A.U.",
    mrp: 429.38,
    rate: 48.12,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524626/Chymothal_Forte_bgcjck.png",
  },
  {
    id: "canrant-cream",
    name: "Canrant Cream",
    content: "Clotrimazole Cream IP",
    form: "Cream",
    mg: "15g",
    mrp: 42.19,
    rate: 11.25,
    unitOfSale: "Tube",
    unitName: "Tube",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524621/Canrant_Crea_m_fmhhxk.png",
  },
  {
    id: "bilaford-20",
    name: "BILAFORD-20",
    content: "Bilastine Tablets IP",
    form: "Tablet",
    mg: "20 mg",
    mrp: 121.88,
    rate: 30,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524619/BILAFORD-20_btqbla.png",
  },
  {
    id: "cefporant-200",
    name: "Cefporant- 200",
    content: "Cefpodoxime Dispersible Tablets 200 mg",
    form: "Tablet",
    mg: "200 mg",
    mrp: 464.06,
    rate: 53.12,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524621/Cefporant-_200_yl1wx7.png",
  },
  {
    id: "dp-gesic",
    name: "DP Gesic",
    content: "DICLOFENAC SODIUM & PARACETAMOL TABLETS I.P. (50mg+325mg)",
    form: "Tablet",
    mg: "50mg+325mg",
    mrp: 31.03,
    rate: 7.19,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524625/DP_GESIC_ltafh9.png",
  },
  {
    id: "dermibit-5-neo-cream",
    name: "Dermibit-5 Neo Cream",
    content: "Clotrimazole, Iodochlorhydroxyquinoline, Tolnaftate, Gentamicin Sulphate & Clobetasol Propionate Cream",
    form: "Cream",
    mg: "15gm",
    mrp: 89,
    rate: 16.88,
    unitOfSale: "Tube",
    unitName: "Tube",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524626/Cernbit_5_cream_c7orzu.png",
  },
  {
    id: "duphill",
    name: "Duphill",
    content: "Doxofylline Tablets IP",
    form: "Tablet",
    mg: "400 mg",
    mrp: 93.7,
    rate: 36.25,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524627/Duphill_fi8pxv.png",
  },
  {
    id: "altam-25",
    name: "ALTAM-25",
    content: "Hydroxyzine Hydrochloride Tablets I.P. (25 mg)",
    form: "Tablet",
    mg: "25 mg",
    mrp: 37.5,
    rate: 7.5,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524617/ALTAM-25_kv9vgb.png",
  },
  {
    id: "bitagesic-gel",
    name: "BITAGESIC GEL",
    content: "Diclofenac Diethylamine, Virgin Linseed Oil, Methyl Salicylate & Menthol Gel",
    form: "Gel",
    mg: "30 g",
    mrp: 120,
    rate: 14.38,
    unitOfSale: "Tube",
    unitName: "Tube",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524619/BITAGESIC_GEL_sqloeo.png",
  },
  {
    id: "duopium-respules",
    name: "DUOPIUM Respules",
    content: "Levosalbutamol and Ipratropium Bromide Respirator Solution",
    form: "Respules",
    mg: "2.5 ml",
    mrp: 37,
    rate: 7.5,
    unitOfSale: "Box",
    unitName: "Respule",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524628/DUOPIUM_few2bl.png",
  },
  {
    id: "azicip-500",
    name: "Azicip 500",
    content: "Azithromycin Tablets IP 500 mg",
    form: "Tablet",
    mg: "500 mg",
    mrp: 75.53,
    rate: 44.38,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524618/Azicip-500_dghb2e.png",
  },
  {
    id: "accerant-sp",
    name: "Accerant-SP",
    content: "Aceclofenac, Paracetamol & Serratiopeptidase Tablets",
    form: "Tablet",
    mg: "100mg+325mg+15mg",
    mrp: 131.25,
    rate: 13.12,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524617/Accerant-SP_rxdcma.png",
  },
  {
    id: "ferorant-xt",
    name: "Ferorant-XT",
    content: "Ferrous Ascorbate, Folic Acid & Zinc Sulphate Tablets",
    form: "Tablet",
    mg: "Standard",
    mrp: 164.06,
    rate: 20.62,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524630/Ferorant-XT_c9hkqw.png",
  },
  {
    id: "fungibit-150",
    name: "FUNGIBIT 150",
    content: "Fluconazole Tablets IP 150 mg",
    form: "Tablet",
    mg: "150 mg",
    mrp: 12.88,
    rate: 4.5,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524616/FUNGIBIT_150_obxwb9.png",
  },
  {
    id: "ketoc",
    name: "KETOC",
    content: "Ketoconazole Tablets I.P.",
    form: "Tablet",
    mg: "200 mg",
    mrp: 103.13,
    rate: 23.75,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524618/KETOC_skcrxb.png",
  },
  {
    id: "nimubit-plus-gold",
    name: "NIMUBIT PLUS GOLD",
    content: "NIMESULIDE & PARACETAMOL TABLETS",
    form: "Tablet",
    mg: "100mg+325mg",
    mrp: 42.15,
    rate: 4.69,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524619/NIMUBIT_PLUS_GOLD_w6vwm2.png",
  },
  {
    id: "mokcan-250-dt",
    name: "MOKCAN 250 DT",
    content: "AMOXCYCILLIN TRIHYDRATE DISPERSIBLE TABLETS IP 250 mg",
    form: "Tablet",
    mg: "250 mg",
    mrp: 62.53,
    rate: 16.88,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524619/MOKCAN_250_DT_mjtswj.png",
  },
  {
    id: "moxiline-cv-625",
    name: "Moxiline CV 625",
    content: "Amoxycillin and Potassium Clavulanate Tablets IP 625 mg",
    form: "Tablet",
    mg: "625 mg",
    mrp: 192,
    rate: 65,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524619/Moxiline_CV_625_gcbqpx.png",
  },
  {
    id: "nogacid-d",
    name: "NOGACID D",
    content: "OMEPRAZOLE & DOMPERIDONE CAPSULES IP (20mg+10mg)",
    form: "Capsule",
    mg: "20mg+10mg",
    mrp: 140,
    rate: 15.31,
    unitOfSale: "Box",
    unitName: "Capsule",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524621/NOGACID-D_ibosay.png",
  },
  {
    id: "mokcan-500",
    name: "MOKCAN-500",
    content: "AMOXYCILLIN CAPSULES IP 500 mg",
    form: "Capsule",
    mg: "500 mg",
    mrp: 77.18,
    rate: 30.62,
    unitOfSale: "Box",
    unitName: "Capsule",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524618/MOKCAN-500_fpac9b.png",
  },
  {
    id: "histolate",
    name: "HISTOLATE",
    content: "Phenylephrine Hydrochloride, Chlorpheniramine Maleate, Caffeine & Paracetamol Tablets",
    form: "Tablet",
    mg: "Standard",
    mrp: 35.6,
    rate: 6.25,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524617/HISTOLATE_nsvwi4.png",
  },
  {
    id: "oflotas-oz",
    name: "OFLOTAS-OZ",
    content: "OFLOXACIN & ORNIDAZOLE TABLETS I.P.",
    form: "Tablet",
    mg: "200mg+500mg",
    mrp: 145.31,
    rate: 23.75,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524620/OFLOTAS-OZ_qexwpk.png",
  },
  {
    id: "safizim-200-dt",
    name: "SAFIZIM 200 DT",
    content: "Cefixime Dispersible Tablets IP (200 mg)",
    form: "Tablet",
    mg: "200 mg",
    mrp: 104.48,
    rate: 37.5,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524626/SAFIZIM_200_DT_gvdfls.png",
  },
  {
    id: "pantoluc",
    name: "Pantoluc",
    content: "Pantoprazole Gastro-Resistant Tablets IP 40mg",
    form: "Tablet",
    mg: "40 mg",
    mrp: 106.85,
    rate: 9.38,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524622/Pantoluc_j63jkr.png",
  },
  {
    id: "pregabanyl-m-75-sr",
    name: "Pregabanyl-M 75 SR",
    content: "Pregabalin (Sustained-release) & Mecobalamin Tablets",
    form: "Tablet",
    mg: "75 mg",
    mrp: 135.9,
    rate: 41.25,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524627/PregabanyI-M_75_SR_aldyqv.png",
  },
  {
    id: "pentorant-dsr",
    name: "Pentorant DSR",
    content: "Pantoprazole Sodium Gastro-resistant & Domperidone Prolonged-release Capsules IP",
    form: "Capsule",
    mg: "40mg+30mg",
    mrp: 117.19,
    rate: 13.12,
    unitOfSale: "Box",
    unitName: "Capsule",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524624/Pentorant_DSR_Capsules_xa0hyc.png",
  },
  {
    id: "rednisol-16",
    name: "Rednisol-16",
    content: "Methylprednisolone Tablets IP (16 mg)",
    form: "Tablet",
    mg: "16 mg",
    mrp: 101.25,
    rate: 38.12,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524623/Rednisol-16_n4lhbh.png",
  },
  {
    id: "pentorant-injection",
    name: "Pentorant Injection",
    content: "Pantoprazole for Injection IP 40mg",
    form: "Injection",
    mg: "40 mg",
    mrp: 53.89,
    rate: 10.62,
    unitOfSale: "Vial",
    unitName: "Vial",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524624/Pentorant-Inj_yoatl6.png",
  },
  {
    id: "pantoluc-d",
    name: "Pantoluc D",
    content: "Pantoprazole Gastro-Resistant and Domperidone Tablets",
    form: "Tablet",
    mg: "40mg+10mg",
    mrp: 120.94,
    rate: 10,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524621/Pantoluc_D_nahevw.png",
  },
  {
    id: "rabegard",
    name: "Rabegard",
    content: "Rabeprazole Tablets IP 20 mg",
    form: "Tablet",
    mg: "20 mg",
    mrp: 68.06,
    rate: 9.38,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524624/Rabegard_js2fph.png",
  },
  {
    id: "nogacid",
    name: "NOGACID",
    content: "OMEPRAZOLE CAPSULES IP 20 mg",
    form: "Capsule",
    mg: "20 mg",
    mrp: 49,
    rate: 10.62,
    unitOfSale: "Box",
    unitName: "Capsule",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524621/NOGACID_wqeixn.png",
  },
  {
    id: "trantas-em",
    name: "Trantas - EM",
    content: "Tranexamic Acid & Etamsylate Tablets",
    form: "Tablet",
    mg: "Standard",
    mrp: 251.25,
    rate: 45,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524627/Trantas_-_EM_pzg3bp.png",
  },
  {
    id: "tensartan-40",
    name: "Tensartan- 40",
    content: "Telmisartan Tablets IP (40 mg)",
    form: "Tablet",
    mg: "40 mg",
    mrp: 70.31,
    rate: 7.5,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524627/Tensartan-_40_ig0hij.png",
  },
  {
    id: "vomistop",
    name: "VOMISTOP",
    content: "Domperidone Tablets IP 10 mg",
    form: "Tablet",
    mg: "10 mg",
    mrp: 24.25,
    rate: 8.12,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524628/VOMISTOP_bsipir.png",
  },
  {
    id: "vominil-md",
    name: "VOMINIL-MD",
    content: "Ondansetron Orally Disintegrating Tablets IP",
    form: "Tablet",
    mg: "4 mg",
    mrp: 54.84,
    rate: 4.88,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524628/VOMINIL-MD_nnzdio.png",
  },
  {
    id: "vertiford-16",
    name: "Vertiford-16",
    content: "Betahistine Hydrochloride Tablets IP (16 mg)",
    form: "Tablet",
    mg: "16 mg",
    mrp: 78.75,
    rate: 13.12,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1762524628/Vertiford-16_n9qpja.png",
  }, // listing batch 3
  {
    id: "cefydoc-ax-500",
    name: "Cefydoc-AX 500",
    content: "Cefuroxime Axetil Tablets I.P.",
    form: "Tablet",
    mg: "500 mg",
    mrp: 230,
    rate: 76.6,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295288/CefyDoc-AX_500_xzhqqf.png",
  },
  {
    id: "ciprolink-500",
    name: "Ciprolink-500",
    content: "Ciprofloxacin Tablets I.P. 500 mg.",
    form: "Tablet",
    mg: "500 mg",
    mrp: 42,
    rate: 29.9,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295289/Ciprolink-500_nciv4f.png",
  },
  {
    id: "cardipin-retard",
    name: "Cardipin Retard",
    content: "Nifedipine Extended Release Tablets IP 20 mg",
    form: "Tablet",
    mg: "20 mg",
    mrp: 14,
    rate: 7.423,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295288/Cardipin_Retard_bk80vg.png",
  },
  {
    id: "eldervit-12",
    name: "Eldervit '12'",
    content: "Vitamin C Injection IP &amp; Vitamin B, Folic Acid &amp; Niacinamide Injection",
    form: "Injection",
    mg: "2.5 ml",
    mrp: 33.0,
    rate: 12.558,
    unitOfSale: "Ampoule",
    unitName: "Ampoule",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295286/Eldervit_12_clq0s0.png",
  },
  {
    id: "hipres-25",
    name: "Hipres-25",
    content: "Atenolol Tablets IP 25 mg",
    form: "Tablet",
    mg: "25 mg",
    mrp: 36,
    rate: 10.062,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295291/Hipres-_25_jxeuba.png",
  },
  {
    id: "norcin-400",
    name: "Norcin 400",
    content: "Norfloxacin Tablets IP 400 mg",
    form: "Tablet",
    mg: "400 mg",
    mrp: 47,
    rate: 23.4,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295299/Norcin_400_Tablets_dzffsm.png",
  },
  {
    id: "zencid-mps",
    name: "ZENCID MPS",
    content: "Alumina, Magnesia &amp; Simethicone Oral Suspension IP",
    form: "Suspension",
    mg: "170 ml",
    mrp: 109,
    rate: 25.5,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295294/ZENCID_MPS_ncu6tt.png",
  },
  {
    id: "calcitas-d3",
    name: "CALCITAS-D3",
    content: "Cholecalciferol Granules 60,000 IU",
    form: "Sachet",
    mg: "1g",
    mrp: 38,
    rate: 7.8,
    unitOfSale: "Box",
    unitName: "Sachet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295287/CALCITAS-D3_bhxbll.png",
  },
  {
    id: "coldlink-cf",
    name: "Coldlink-CF",
    content: "Paracetamol, Caffeine, Phenylephrine HydroChloride &amp; Chlorpheniramine Maleate Tablets",
    form: "Tablet",
    mg: "Standard",
    mrp: 56.25,
    rate: 8.45,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295291/Coldlink-CF_i9cwtl.png",
  },
  {
    id: "ceprozone-s",
    name: "CEPROZONE-S",
    content: "CEFOPERAZONE &amp; SULBACTAM FOR INJECTION",
    form: "Injection",
    mg: "1.5 g/Vial",
    mrp: 563,
    rate: 61.5,
    unitOfSale: "Vial",
    unitName: "Vial",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295288/CEPROZONE-S_ndjpl6.png",
  },
  {
    id: "novacort-100mg",
    name: "NOVACORT",
    content: "Hydrocortisone Sodium Succinate Injection IP",
    form: "Injection",
    mg: "100 mg",
    mrp: 47,
    rate: 24.05,
    unitOfSale: "Vial",
    unitName: "Vial",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295292/NOVACORT_INJ_xarakb.png",
  },
  {
    id: "zenlactin-200ml",
    name: "Zenlactin",
    content: "Cyproheptadine Hydrochloride &amp; Tricholine Citrate Oral Liquid",
    form: "Syrup",
    mg: "200 ml",
    mrp: 150,
    rate: 42.9,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295286/enlactin_200_ml_caxvbj.png",
  },
  {
    id: "zybend-tablet",
    name: "Zybend",
    content: "Albendazole Tablets IP",
    form: "Tablet",
    mg: "400 mg",
    mrp: 9,
    rate: 3.64,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295294/Zybend_tpxwav.png",
  },
  {
    id: "nor-tz",
    name: "Nor-TZ",
    content: "Norfloxacin &amp; Tinidazole Tablets",
    form: "Tablet",
    mg: "400mg+600mg",
    mrp: 42,
    rate: 22.75,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295294/Nor_T_Z_Tab_grobyb.png",
  },
  {
    id: "milmafin-plus-170ml",
    name: "Milmafin Plus",
    content: "MILK OF MAGNESIA, LIQUID PARAFFIN &amp; SODIUM PICOSULFATE SUSPENSION",
    form: "Suspension",
    mg: "170 ml",
    mrp: 181,
    rate: 52.5,
    unitOfSale: "Bottle",
    unitName: "Bottle",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295291/Milmafin_Plus_ejmytg.png",
  },
  {
    id: "flexib-325",
    name: "FLEXIB 325",
    content: "Ibuprofen and Paracetamol Tablets IP",
    form: "Tablet",
    mg: "400mg+325mg",
    mrp: 36,
    rate: 26.65,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295287/FLEXIB_325_t5kf05.png",
  },
  {
    id: "doxneed-lb",
    name: "DOXNEED-LB",
    content: "Doxycycline HCl &amp; Lactic Acid Bacillus Capsules",
    form: "Capsule",
    mg: "100mg",
    mrp: 121,
    rate: 24,
    unitOfSale: "Box",
    unitName: "Capsule",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295292/DOXNEED_LB_o5tfdb.png",
  },
  {
    id: "calciquick-d3-60k",
    name: "Calciquick-D3 60K",
    content: "Cholecalciferol Chewable Tablets 60,000 IU",
    form: "Tablet",
    mg: "60,000 IU",
    mrp: 102,
    rate: 26.25,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295287/Calciquick-D360_K_kuct4b.png",
  },
  {
    id: "mecofar-plus-inj",
    name: "Mecofar Plus",
    content: "Methylcobalamin, Vitamin B1, B6, Niacinamide &amp; D-Panthenol Injection",
    form: "Injection",
    mg: "2 ml",
    mrp: 75,
    rate: 14.95,
    unitOfSale: "Box",
    unitName: "Vial",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295288/Mecofar_Plus_ytkhiz.png",
  },
  {
    id: "atenolol-50mg",
    name: "Atenolol 50 mg",
    content: "Atenolol Tablets I.P. 50 mg",
    form: "Tablet",
    mg: "50 mg",
    mrp: 34,
    rate: 8.45,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295286/Atenoloi_Tablets_I.P_50mg_drdcqx.png",
  },
  {
    id: "amlip-2-5",
    name: "Amlip-2.5",
    content: "Amlodipine Besilate Tablets IP 2.5 mg",
    form: "Tablet",
    mg: "2.5 mg",
    mrp: 20,
    rate: 8.45,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295286/Amlip-2.5_po170r.png",
  },
  {
    id: "myformin-500-sr",
    name: "MYFORMIN-500 SR",
    content: "Metformin Hydrochloride Prolonged-release Tablets IP 500 mg",
    form: "Tablet",
    mg: "500 mg",
    mrp: 23,
    rate: 11.05,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295290/MYFORMIN-500_SR_hlikbc.png",
  },
  {
    id: "ranish-150",
    name: "Ranish-150",
    content: "Ranitidine Hydrochloride Tablets IP 150 mg",
    form: "Tablet",
    mg: "150 mg",
    mrp: 15,
    rate: 7.8,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295294/Ranish-150_n3hx1g.png",
  },
  {
    id: "dano-tt",
    name: "DANO-TT",
    content: "Tetanus Vaccine (Adsorbed) I.P.",
    form: "Vaccine",
    mg: "0.5 ml",
    mrp: 13.5,
    rate: 11.7,
    unitOfSale: "Box",
    unitName: "Ampoule",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295294/Tetanus_Vaccine_Adsorbed_I.P_yvgkup.png",
  },
  {
    id: "biodipin-5",
    name: "BIODIPIN-5",
    content: "AMLODIPINE TABLETS IP",
    form: "Tablet",
    mg: "5 mg",
    mrp: 28,
    rate: 5.475,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295286/BIODIPIN-5_eywkmk.png",
  },
  {
    id: "doxocip",
    name: "DOXOCIP",
    content: "Doxofylline Tablets IP 400 mg",
    form: "Tablet",
    mg: "400 mg",
    mrp: 91,
    rate: 36.75,
    unitOfSale: "Box",
    unitName: "Tablet",
    imageUrl: "https://res.cloudinary.com/dfvqt9wcy/image/upload/v1763295293/DOXOCIP_qqa2om.png",
  },
];
